nome=input("Boa noite, estudante, poderia me dizer o seu nome? ")
print("Seu nome é", nome, "certo? Agora vamos para a próxima etapa...")
sobrenome=input("Agora pode me dizer o seu sobrenome? ")
print("Certo," , nome , sobrenome)
profissao=input("Agora pode me informar qual é a sua profissão? ")
print("Sua profissão é", profissao, "legal! Vamos seguir...")
idade=input("Qual é a sua idade? ")
print(f'Sua idade é {idade} anos')
esporte=input(f'Da família {sobrenome}, qual é o esporte favorito? ')
print(f'O esporte favorito da família {sobrenome} é o {esporte}...')
print("...e eu não dou a mínima! I don't give a shit")